### ISSUE TITLE
shouldn't $forge->runRecipe($recipeId); include a way to pass server ids?

### ISSUE THREAD

**Issue by vesper8** [themsaid/forge-sdk#13]
Just wondering how you can run a recipe on a specific server or set of servers

in the api docs the payload is described as 
```
⊖{
    "servers": ⊖[
        1,
        2
    ]
}
```

but according to your docs the runRecipe() only accepts a recipeId?

**Comment by jpmurray** [comment]
I haven't tried it yet, but if you look at the usage section, you probably can run recipes like so:

```php
$server = $forge->server(SERVER_ID_HERE);
$server->->runRecipe($recipeId);
```

**Comment by svenluijten** [comment]
@jpmurray no, since recipes can be run on multiple servers at once. Adding it to the `Server` class wouldn't make sense. I've opened a PR (#19) to address this issue 🙂
