### ISSUE TITLE
rate limiting (too many attempts)

### ISSUE THREAD

**Issue by vesper8** [themsaid/forge-sdk#14]
I've written a script that basically exports everything from the forge api and stores it in a local database and with 10 servers and 160 sites I am running into the 429 Too Many Attempts error.

However in the api docs I am unable to see anything about a rate limit, and also I don't have experience with setting a rate limit locally so I don't hammer the api.

Any chance you could introduce this? Or at least provide some directions on how I could easily achieve this (the proper way) so I can run my "populate" script in the future and not fear of running into the "Too many attempts" limit?

Many thanks

**Comment by johnpbloch** [comment]
The rate limit is 30 requests. I think it's per minute, but it could be per 5 minutes (I haven't done extensive testing).

The forge API sends a response header telling you how many requests you have remaining. If you wanted to get that information, you can pass an instance of guzzle's `HttpClient` as the second argument of the `Forge` class that has some kind of middleware that can keep a timer going and check the rate limit for you on each request.

**Comment by vesper8** [comment]
Thanks a lot for your suggestion! I just implemented something that is working. It's my first time adding a Guzzle middleware. Thanks to this modification I am now able to do a FULL fetch on my 10+ forge servers and get every little detail about each server and each site without running into the rate limiting

In case it helps anyone else, here's a sample of my code

```
<?php

namespace App\Helpers;

use Psr\Http\Message\ResponseInterface;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Handler\CurlHandler;
use GuzzleHttp\Client;
use GuzzleHttp\Middleware;
use Themsaid\Forge\Forge;

class ForgeHelpers
{
    protected $forge;
    protected $guzzle;

    protected $remainingApiCallsThisMinute=0;

    public function initForge()
    {
        $stack = new HandlerStack();
        $stack->setHandler(new CurlHandler());

        $stack->push(Middleware::mapResponse(function (ResponseInterface $response) {
            $headers = $response->getHeaders();

            $this->remainingApiCallsThisMinute = $headers['X-RateLimit-Remaining'][0];

            return $response;
        }));

        $this->guzzle = new Client([
            'base_uri' => 'https://forge.laravel.com/api/v1/',
            'http_errors' => false,
            'headers' => [
                'Authorization' => 'Bearer ' . config('services.forge.token'),
                'Accept' => 'application/json',
                'Content-Type' => 'application/json'
            ],
            'handler' => $stack,
        ]);

        $this->forge = new Forge(config('services.forge.token'), $this->guzzle);

        return $this->forge;
    }

    public function populate($type, $model, $params = [])
    {
        $serverId = $siteId = "";
        if(isset($params['server_id']))
            $serverId = " ServerId:{$params['server_id']}";
        if(isset($params['site_id']))
            $siteId = " SiteId:{$params['site_id']}";

        \Log::info("Fetching {$type}...{$serverId}{$siteId}");

        // fetch the data from forge api

        \Log::info("{$this->remainingApiCallsThisMinute} api calls remaining...");

        if($this->remainingApiCallsThisMinute == 1) {
            \Log::info('Pausing for 60 seconds');
            sleep(60);
        }

        // do something with fetched data

    }

}
```

**Comment by vesper8** [comment]
The above method worked well for me as long as I was only using a single queue worker for performing api calls. But as soon as I tried it with multiple workers it collapsed quickly.. 

I suspect race conditions. I tried other recommended methods of adding rate limiting but none of them work perfectly. I open an issue on the main laravel repo seeking helps from smarter people than myself https://github.com/laravel/framework/issues/21346

**Comment by chrisvickers** [comment]
I found the limit, Postman has told me i have 60 requests a minute. Kind of seems low as i am also coming into the same problem. I have 4 servers, each with around 160 sites.

Considering this is a paid service i would think being able to handle more than 60 request a minute would be easy to implement by upgrading server infrastructure. 

I would prefer not to limit my application speed due to a request limit on forge's side.

**Comment by vesper8** [comment]
@themsaid here https://github.com/laravel/framework/issues/21346#issuecomment-331850513 you said you were going to increase the limit.. but it seems like you never did? It is still capped at 60 / second ?

It would be nice if you increased it, and it would be even nicer if you added some functionality to this package to innately respect this limit

**Comment by themsaid** [comment]
After discussions with Taylor he decided that the rate limit will remain as is for now, we might increase it in the future but such like any other paid/un-paid service, a rate limit is a must to prevent abusive usage of our APIs.
