### ISSUE TITLE
Exclude "archived" servers?

### ISSUE THREAD

**Issue by drbyte** [themsaid/forge-sdk#15]
`$forge->servers();` includes "archived" servers.

Perhaps that's because `GET /api/v1/servers` doesn't indicate whether a server is archived vs active?

**Comment by phppirate** [comment]
Thank You for your interest in Anvil.
This does not seem to be a documented feature yet. Will add it as soon as possible.

**Comment by themsaid** [comment]
What do you mean by `archived`?

**Comment by themsaid** [comment]
But you already receive the `revoked` key in the response, if its value is `true` then it's an archived server.

**Comment by drbyte** [comment]
Okay, thanks. I hadn't associated "revoked" with "archived".  Thanks!
