### ISSUE TITLE
Reboot Server not found

### ISSUE THREAD

**Issue by phppirate** [themsaid/forge-sdk#16]
I cannot seem to find a way to reboot a server using this SDK.

**Comment by svenluijten** [comment]
Does `->rebootServer()` not work for you? https://github.com/themsaid/forge-sdk/blob/master/src/Actions/ManagesServers.php#L99-L108 🙂

**Comment by phppirate** [comment]
I am sure that will work 🙂 but it is not documented. Thank you for pointing it out.
