### ISSUE TITLE
Running code after site deployment

### ISSUE THREAD

**Issue by hugoburguete** [themsaid/forge-sdk#21]
I have a deployment script that creates a database with a couple of tables and I was hoping I could run some php code after the deployment to populate those tables. Is there a way to sync to forge's deployment?

**Comment by svenluijten** [comment]
You could utilize Forge's default deployment script for this. Put the file on your server and call it in the script (`php /path/to/your/file.php`, or any other way 😉).

**Comment by hugoburguete** [comment]
The only issue with that is that the file will run everytime a deployment is made. I don't want to be adding users everytime I make a code change and deploy it.

**Comment by themsaid** [comment]
We're planning a post-deployment webhook solution, but no ETA yet :)

**Comment by hugoburguete** [comment]
Thanks. Closing ticket
