### ISSUE TITLE
Installing certificates inconsistent with API docs

### ISSUE THREAD

**Issue by svenluijten** [themsaid/forge-sdk#26]
Installing an SSL certificate accepts a payload (as documented [here](https://forge.laravel.com/api-documentation#install-certificate)), but the SDK [doesn't seem to do so](https://github.com/themsaid/forge-sdk/blob/master/src/Actions/ManagesCertificates.php#L100). I'm unsure whether or not this is an issue with Forge's documentation or an issue on this SDK, I'll let you decide that 😉 

Thanks in advance.

**Comment by jclark-mossio** [comment]
Ran into the same issue.

**Comment by themsaid** [comment]
fixed
