### ISSUE TITLE
create site then update site configurations - 502 error

### ISSUE THREAD

**Issue by essaaam** [themsaid/forge-sdk#27]
Hello,

When I make a new site and in the same request edit the new site nginx file I get 502 error :(

I hope you can help me with that

Thanks

**Comment by acacha** [comment]
Same problem here!

**Comment by svenluijten** [comment]
Probably because the site is still being made? AFAIK Forge is all queued jobs, so you might be trying to edit a site that doesn't exist yet.

**Comment by acacha** [comment]
The problem in my case is using Forge SDK commands with wait=true like 

```
$forge->createSite($serverId, array $data, $wait = true);
```

In fact there is no way to execute this commands in my own api call when client I use to execute commands is Guzzle and connection use SSL. It seems Guzzle always get a response without content or a timeout waiting for response.

**Comment by jclark-mossio** [comment]
I am seeing the same issue

**Comment by themsaid** [comment]
please let me know if you're still facing the issue and share more details.

**Comment by gerciljunio** [comment]
@themsaid I am still experiencing this problem in the latest version, the error involves several problems, however, I have already increased the capacity of fastcgi, I have already made several modifications in nginx, I have already increased the memory of the server and continues the same problem. unhappy, I do not know what else to do! lol. if you have any suggestion I'm grateful...

error in nginx log:

```
[error] 12194#12194: *10 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 189.15.187.187, server: toaberto.com, request: "POST /manage/account/custom HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "toaberto.com", referrer: "https://toaberto.com/manage/account"
```

thanks!

**Comment by themsaid** [comment]
@gerciljunio I'm not sure it's the same issue, can you please share more details? Or maybe open a new issue.

**Comment by gerciljunio** [comment]
@themsaid is the same problem, 502 bad gateway and really like the @acacha said, it's happening in:

```
$forge->createSite($serverId, array $data, $wait = true);
```

this morning, I solved the problem, leaving `$wait = false` and creating a queue which creates the site using the "createSite" method and then checks if the site has already been created and everything is ok using the "site" method and continues the process after the verification completed successfully.

but when I actually leave `$wait = true` it occurs the 502 error even increasing the timeout and sizes of nginx and php on the server.

you asked for more details, my code was like this:

```
try {
    $site = $forge->createSite('XXX', [
        'domain' => $siteHost,
        'project_type' => 'php',
        'directory' => '/public'
    ]);
} catch (\Exception $e) {
    return redirect()->route('app.account');
}
```

and to work in the queue, it looks like this:

```
try {
    $site = $forge->createSite('XXX', [
        'domain' => $siteHost,
        'project_type' => 'php',
        'directory' => '/public'
    ], false);
} catch (\Exception $e) {
    //error handling
}
```

detail, if I leave the `$wait = true` also happens the same error in the queue, so in the end really only worked with `$wait = false`

thanks for your attention!

**Comment by RoseRiyadh** [comment]
> 

where do I find this block of code?
