### ISSUE TITLE
Having issue running some methods on forge API

### ISSUE THREAD

**Issue by chiragparekh** [themsaid/forge-sdk#37]
Hi,
I managed to run following methods:

$forge->createSite($server_id,$site_data, true);
$forge->installGitRepositoryOnSite($server_id, $site_id, $repository_data);
$forge->updateSiteDeploymentScript($server_id, $site_id, $content);

But following commands doesn't take any effects. Is there any specific needs to run the following commands:

 $forge->updateSiteEnvironmentFile($server_id, $site_id, $content);
$forge->deploySite($server_id,$site_id);

**Comment by mubeen-gs** [comment]
@chiragparekh I had the same issue. You need to check the `$site->repositoryStatus` and wait until it is `'installed'`, then move on.

Below is an example method that will only continue once the repo has been installed:

```php
<?php

    /**
     * @param \Themsaid\Forge\Forge $forge
     * @param int $serverId
     * @param \Themsaid\Forge\Resources\Site $site
     * @return bool
     * @throws \App\Exceptions\InstallGitRepositoryException
     */
    protected function installGitRepository(Forge $forge, int $serverId, Site $site): bool
    {
        $site->installGitRepository([
            'provider' => 'github',
            'repository' => 'vendor/repo',
            'branch' => 'master',
        ]);

        $start = time();

        beginning:

        if ($site->repositoryStatus === 'installed') {
            return true;
        }

        if (time() - $start < 60) {
            sleep(5);
            $site = $forge->site($serverId, $site->id);
            goto beginning;
        }

        throw new InstallGitRepositoryException();
    }
```

**Comment by chiragparekh** [comment]
Hi, @mubeen-gs ,

I just checked the code and it solved my issue. Thank you for you help.

I am closing the ticket now.
