### ISSUE TITLE
The given data failed to pass validation.

### ISSUE THREAD

**Issue by mckayze** [themsaid/forge-sdk#47]
I keep getting this error when attempting to create a new server on forge using the code below

**The given data failed to pass validation.**

````
$this->forge->createServer([
    'provider' => 'aws',
    'credential_id' => 1,
    'name' => 'fancy-mist',
    'size' => '1GB',
    'php_version' => 'php72',
    'region' => 'London',
]);
````

I can use the following code on the same setup successfully and I don't get this error.

````
$this->forge->servers();
````

Not sure why this is happening, if there is any more info you need please ask and i'll provide it.

**Comment by VictorAvelar** [comment]
@themsaid I think this exposes the reason behind #46 as I think the error is in the AWS region name.

@mckayze can you confirm this using the `/api/v1/regions`endpoint, please?

**Comment by mckayze** [comment]
@VictorAvelar Ive tried using a mixture of `eu-west-1` / `London`. The documentation on forge isn't very thorough. I read through your issue #46 and looks like a solid idea / way to upgrade the simplicity of this SDK & help people with forge on a whole anyway.

From the `/api/v1/regions` endpoint under london in AWS i get this response

```
    3 => array:3 [▼
        "id" => "eu-west-2"
        "name" => "London"
        "sizes" => array:16 [▼
          0 => array:3 [▼
            "id" => "01"
            "size" => "t2.nano"
            "name" => "1 vCPUs - 0.5GB RAM (t2.nano)"
          ]
    ]
```

**Comment by themsaid** [comment]
The exception class has more details, check `Themsaid\Forge\Exceptions\ValidationException@errors()`
