### ISSUE TITLE
installCertificate: The given data failed to pass validation.

### ISSUE THREAD

**Issue by francisco-ltech** [themsaid/forge-sdk#48]
Hi there,

I get this error when calling $forge->installCertificate

but not much information is shown about the error: The given data failed to pass validation. {"exception":"[object] (Themsaid\\Forge\\Exceptions\\ValidationException(code: 0): The given data failed to pass validation. at /vendor/themsaid/forge-sdk/src/MakesHttpRequests.php:90)

Error doesn't specify why it failed validation.

I believe there is a similar ticket but this is for a different api method.

UPDATE1: 0 => "The certificate field is required."
But I'm definitely passing the certificate id. 

UPDATE2: I might be using the sdk wrong. What I want to do is: I already have a certificate installed for my a site and want to install it for other sites. Is there a specific API workflow I should follow? The official api docs says: "certificate": "certificate content", but I have no idea what "certificate content" means or where to get it from?

**Comment by KevinBatdorf** [comment]
Just to add, I believe I had the same error when attempting to install WordPress via the API as well. I don't think it gave any extra details either.

**Comment by themsaid** [comment]
Check the exception class `Themsaid\Forge\Exceptions\ValidationException` you will find more details in the $errors property.
