### ISSUE TITLE
[SUGGESTION] CLI options 

### ISSUE THREAD

**Issue by Christophvh** [themsaid/forge-sdk#54]
Would be nice to have command line calls so we could include some forge-commands in an automated docker/ci setup for example.

There are a couple of options available like: https://github.com/svenluijten/forge-cli
But I think this is useful enough to be included in the API.

**Comment by svenluijten** [comment]
I'm not sure how you'd like to see this implemented in the SDK / API?

**Comment by Christophvh** [comment]
I missed that your package was a global-package I confused it for an install in a project, which was not my use-case, but your package solves the problem !
